title: Home Credit Risk
description: Our documentation website for the semester-long Graduate Machine Learning (CS 7641) project, by Reetesh Sudhakar, Nityam Bhachawat, Mark Glinberg, and Yash Gupta.
theme: just-the-docs

url: https://just-the-docs.github.io
aux_links:
    Code Repository: https://github.com/reeteshsudhakar/CS-7641-Project
